config/routes.rb
DiveIn::Application.routes.draw do

  devise_for :users
  root "home#index"

  get 'home' => "home#index"
  get 'about' => "home#about"

  resources :categories, only:[:show] do
    resources :divesites, only:[:index]
  end

  resources :months, only:[:show] do
    resources :divesites, only:[:index]
  end

  resources :divesites, only:[:index, :show, :search] do
    resources :reviews
    collection do
      post 'search', to: 'divesites#index'
    end
  end

  namespace :admin do
    resources :divesites do
      resources :media, only: [:new, :create, :destroy]
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :homes, only:[:index]
  end

end

app/models/divesite.rb
class Divesite < ActiveRecord::Base
  validates :name, presence: true
  validates :country, presence: true
  validates :description, presence: true
  validates :rating, presence: true, inclusion: {:in => 1..5}
  validates :latitude, presence: true
  validates :longitude, presence: true

  has_many :reviews, dependent: :destroy, inverse_of: :divesite
  has_many :divesite_categories
  has_many :categories, through: :divesite_categories
  has_many :divesite_months
  has_many :months, through: :divesite_months
  has_many :media

  def total_review_ratings
    ratings = []
    reviews.all.each do |review|
      ratings << review[:rating]
    end
    ratings
  end

  def average_review_rating
    (total_review_ratings.inject{|sum, review| sum + review}/reviews.all.count).to_f
  end

  def overall_rating
    if reviews.count == 0
      rating.to_f
    elsif reviews.count <= 10
      (rating.to_f * 0.5) + (average_review_rating * 0.5)
    else
      average_review_rating
    end
  end

  class << self
    def search(params)
      query = "%#{params[:name]}%"
      month_ids = params[:months].reject(&:empty?).map{|month| month.to_i}
      category_ids = params[:categories].reject(&:empty?).map{|category| category.to_i}

      divesites = Divesite.all

      if !month_ids.empty?
        divesites = divesites.joins(:months).where("months.id IN (?)", month_ids)
      end

      if !category_ids.empty?
        divesites = divesites.joins(:categories).where("categories.id IN (?)", category_ids)
      end

      if !params[:name].empty?
        divesites = divesites.where("divesites.name ILIKE ? OR divesites.country ILIKE ?", query, query)
      end

      divesites
    end

    def map_data
      Divesite.all.map{|divesite| {latLng: [divesite.latitude, divesite.longitude], name: divesite.name, id: divesite.id}}
    end
  end
end

app/controllers/admin/divesites_controller.rb
module Admin
  class DivesitesController <ApplicationController

    before_action :authorize_user

    def new
      @divesite = Divesite.new
    end

    def create
      @divesite = Divesite.new(divesite_params)
      if @divesite.save
        redirect_to admin_homes_path,
          notice: "New Divesite Successfully Created!"
      else
        render 'new'
      end
    end

    def index
      @divesites = Divesite.order(:name).page(params[:page]).per(1)
    end

    def show
      @divesite = Divesite.find(params[:id])
      @medium = @divesite.media.build
    end

    def edit
      @divesite = Divesite.find(params[:id])
    end

    def update
      @divesite = Divesite.find(params[:id])
      if @divesite.update(divesite_params)
        redirect_to admin_divesite_path(@divesite),
          notice: "Divesite Successfully Updated!"
      else
        render 'edit'
      end
    end

    def destroy
      @divesite = Divesite.find(params[:id])
      @divesite.destroy
        redirect_to admin_divesites_path,
        notice: "Divesite Successfully Removed"
    end

    def destroy_multiple
      Divesite.where(id: params[:site_id]).destroy_all
        redirect_to admin_divesites_path,
        notice: "Divesite(s) Successfully Deleted"
    end

    protected

    def divesite_params
      params.require(:divesite).permit(:name, :region, :country, :latitude, :longitude,
        :description, :surrounding_area, :rating, :water_temperature, :visibility,
        :month_ids => [], :category_ids => [], :medium_ids => [])
    end
  end
end

app/controllers/divesites_controller.rb
class DivesitesController < ApplicationController

  def index
    if params[:q]
      @divesites = Divesite.search(params[:q])
      @divesites.includes([:categories, :months])
    else
      @divesites = Divesite.includes([:categories, :months])
    end
  end

  def show
    @divesite = Divesite.find(params[:id])
    @divesite_images = @divesite.media.all
  end
end

app/views/admin/divesites/_form.html.erb
<%= simple_form_for [:admin, @divesite], html: {multipart: true} do |f| %>

    <%= f.input :name %>
    <%= f.input :region, required: false %>
    <%= f.input :country %>
    <%= f.input :latitude %>
    <%= f.input :longitude %>
    <%= f.input :description %>
    <%= f.input :surrounding_area, required: false %>
    <%= f.input :rating, collection: 1..5 %>
    <%= f.input :water_temperature, required: false %>
    <%= f.input :visibility, required: false %>
    <%= f.association :months, as: :check_boxes %>
    <%= f.association :categories, as: :check_boxes %>
    <%= f.button :submit %>
<%end%>

app/views/admin/divesites/edit.html.erb
<div class="admin-form">
  <h1> Edit Divesite Information </h1>
  <%= render 'form'%>
</div>

app/views/admin/divesites/index.html.erb
<div class="show-header">
  <h1> List of Top Divesites in the World</h1>
</div>

<table align="center">
  <thead>
    <tr>
      <th> Divesite </th>
      <th> Country </th>
    </tr>
  </thead>

  <tbody>
    <%= paginate @divesites %>
    <%= form_tag destroy_multiple_admin_divesites_path, method: :delete do %>
      <%@divesites.each do |site| %>
        <tr>
          <td>
            <%= check_box_tag "site_id[]", site.id%>
            <%= link_to site.name, admin_divesite_path(site.id) %>
          </td>
          <td>
            <%= site.country %>
          </td>
        </tr>
      <%end%>
    <tr>
      <td>
        <%= submit_tag "Delete Selected Divesites", onclick: "return confirm('Are you sure?')"%>
      <%end%>
      </td>
    </tr>
  </tbody>
</table>

app/views/admin/divesites/new.html.erb
<div class="admin-form">
  <h1> Add New Divesite </h1>
  <%= render 'form'%>
</div>

app/views/admin/divesites/show.html.erb
<div class="admin-show">
   <h1 class="show-header"><%= @divesite.name %></h1>

  <% @divesite.media.each do |medium|%>
    <li id="admin-media">
    <% unless @divesite.media.count == 0 %>
      <%=image_tag medium.image.url(:thumb).to_s %>
      <%unless medium.id == nil %>
      <%= link_to "Delete Image", [:admin, @divesite, medium], method: :delete, data: {confirm: "Are you sure?"}%>
      <%end%>
    <%end%>
    </li>
  <%end%>

  <p>
    <strong>Region:</strong>
    <%= @divesite.region %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= @divesite.country %>
  </p>

  <p>
    <strong>Overall Rating:</strong>
    <%= @divesite.rating %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= @divesite.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= @divesite.longitude %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @divesite.description %>
  </p>

  <p>
    <strong>Surrounding Area:</strong>
    <%= @divesite.surrounding_area %>
  </p>

  <p>
    <strong>Average Water Temperature:</strong>
    <%= @divesite.water_temperature %>
  </p>

  <p>
    <strong>Average Visibility:</strong>
    <%= @divesite.visibility %>
  </p>

  <p>
    <strong> Best Known For:</strong>
    <% @divesite.categories.each do |category|%>
    <%=link_to category.name, category_path(category)%><br>
    <%end%>
  </p>

  <p>
    <strong> Best Month(s) of the Year to Dive:</strong>
    <% @divesite.months.each do |month|%>
    <%=link_to month.name, month_path(month)%><br>
    <%end%>
  </p>

  <strong><li> Add Image</li></strong>
  <%= simple_form_for [:admin, @divesite, @medium], html: {multipart: true} do |f| %>
    <%= f.file_field :image%>
    <%= f.button :submit, "Add Image" %>
  <%end%>

  <li><%= link_to "Edit Information", edit_admin_divesite_path(@divesite) %></li>
  <li><%= link_to "Remove Divesite", admin_divesite_path(@divesite), method: :delete, data: {confirm: "Are you sure?"}%></li>
  <li><%= link_to "Back to Divesites List", admin_divesites_path %></li>
</div>