config/routes.rb
DiveIn::Application.routes.draw do

  devise_for :users
  root "home#index"

  get 'home' => "home#index"
  get 'about' => "home#about"

  resources :categories, only:[:show] do
    resources :divesites, only:[:index]
  end

  resources :months, only:[:show] do
    resources :divesites, only:[:index]
  end

  resources :divesites, only:[:index, :show, :search] do
    resources :reviews
    collection do
      post 'search', to: 'divesites#index'
    end
  end

  namespace :admin do
    resources :divesites do
      resources :media, only: [:new, :create, :destroy]
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :homes, only:[:index]
  end

end

app/controllers/admin/homes_controller.rb
module Admin
  class HomesController <ApplicationController

    def index
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @categories = Category.all
    @months = Month.all
    @divesites = Divesite.all

    respond_to do |format|
      format.html
      format.json {render json: {
      markers: Divesite.map_data
        }}
    end
  end

  def about
  end
end

app/views/home/about.html.erb
<div id="about">
  <div id="about-left-box">
    <p>Want to find an awesome divesite but have no idea where to go?</p>
    <p>Want to go dive in January but don't know if it's the right season?</p>
    <p>Dying to see a whale shark but not sure where to find one?</p>
  </div>

  <div id="about-right-box">
    <p>Dont worry, we got you covered</p>
    <p>Just put on your mask and fins</p>
    <p>And get ready to...</p>
    <p><%=link_to "DIVE IN!", root_path%></p>
  </div>
</div>

<% content_for :extra_footer do %>
  <script>
  $(function(){
    slowText();
  })
  </script>
<% end %>

app/views/home/index.html.erb
<h1 class="home-header"> Where Do You Want To Dive? </h1>

<div id="world-map"></div>

<div class="month">
  <h1 class="home-header">Find Divesites By Month</h1><br>
  <ul class="small-block-grid-6">
    <% @months.each do |month|%>
    <li class="button" id="month-button"><%= link_to month.name, month_path(month)%></li>
    <%end%>
  </ul>
</div>

<div id="category">
  <% @categories.each do |category| %>
    <div style="display:none; background-image: url('<%= asset_path(category.image) %>')" class="category-image" data-category="<%= category.name %>">
    </div>
  <% end %>
  <h1 class="home-header">Find Divesites By Category</h1><br>
</div>

<div id="category-all">
  <ul class="small-block-grid-5">
    <% @categories.each do |category| %>
    <li class="button" id="category-button"><%= link_to category.name, category_path(category), class: category.name %></li>
    <% end %>
  </ul>
</div>

<div id="list">
  <h1 class="home-header"><%=link_to 'Search for the Perfect Divesite', divesites_path%></h1>
</div>

<% content_for :javascripts do %>
  <script>
    function changeImage(event){
      var $target = $(event.target);
      $("#category div").hide();
      $("#category div[data-category='" + $target.attr("class") + "']").show();
    }

    $(function(){
      makeMap();
      $('#category-all a').mouseover(changeImage);
    });
  </script>
<%end%>