config/routes.rb
DiveIn::Application.routes.draw do

  devise_for :users
  root "home#index"

  get 'home' => "home#index"
  get 'about' => "home#about"

  resources :categories, only:[:show] do
    resources :divesites, only:[:index]
  end

  resources :months, only:[:show] do
    resources :divesites, only:[:index]
  end

  resources :divesites, only:[:index, :show, :search] do
    resources :reviews
    collection do
      post 'search', to: 'divesites#index'
    end
  end

  namespace :admin do
    resources :divesites do
      resources :media, only: [:new, :create, :destroy]
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :homes, only:[:index]
  end

end

app/models/divesite.rb
class Divesite < ActiveRecord::Base
  validates :name, presence: true
  validates :country, presence: true
  validates :description, presence: true
  validates :rating, presence: true, inclusion: {:in => 1..5}
  validates :latitude, presence: true
  validates :longitude, presence: true

  has_many :reviews, dependent: :destroy, inverse_of: :divesite
  has_many :divesite_categories
  has_many :categories, through: :divesite_categories
  has_many :divesite_months
  has_many :months, through: :divesite_months
  has_many :media

  def total_review_ratings
    ratings = []
    reviews.all.each do |review|
      ratings << review[:rating]
    end
    ratings
  end

  def average_review_rating
    (total_review_ratings.inject{|sum, review| sum + review}/reviews.all.count).to_f
  end

  def overall_rating
    if reviews.count == 0
      rating.to_f
    elsif reviews.count <= 10
      (rating.to_f * 0.5) + (average_review_rating * 0.5)
    else
      average_review_rating
    end
  end

  class << self
    def search(params)
      query = "%#{params[:name]}%"
      month_ids = params[:months].reject(&:empty?).map{|month| month.to_i}
      category_ids = params[:categories].reject(&:empty?).map{|category| category.to_i}

      divesites = Divesite.all

      if !month_ids.empty?
        divesites = divesites.joins(:months).where("months.id IN (?)", month_ids)
      end

      if !category_ids.empty?
        divesites = divesites.joins(:categories).where("categories.id IN (?)", category_ids)
      end

      if !params[:name].empty?
        divesites = divesites.where("divesites.name ILIKE ? OR divesites.country ILIKE ?", query, query)
      end

      divesites
    end

    def map_data
      Divesite.all.map{|divesite| {latLng: [divesite.latitude, divesite.longitude], name: divesite.name, id: divesite.id}}
    end
  end
end

app/controllers/admin/divesites_controller.rb
module Admin
  class DivesitesController <ApplicationController

    before_action :authorize_user

    def new
      @divesite = Divesite.new
    end

    def create
      @divesite = Divesite.new(divesite_params)
      if @divesite.save
        redirect_to admin_homes_path,
          notice: "New Divesite Successfully Created!"
      else
        render 'new'
      end
    end

    def index
      @divesites = Divesite.order(:name).page(params[:page]).per(1)
    end

    def show
      @divesite = Divesite.find(params[:id])
      @medium = @divesite.media.build
    end

    def edit
      @divesite = Divesite.find(params[:id])
    end

    def update
      @divesite = Divesite.find(params[:id])
      if @divesite.update(divesite_params)
        redirect_to admin_divesite_path(@divesite),
          notice: "Divesite Successfully Updated!"
      else
        render 'edit'
      end
    end

    def destroy
      @divesite = Divesite.find(params[:id])
      @divesite.destroy
        redirect_to admin_divesites_path,
        notice: "Divesite Successfully Removed"
    end

    def destroy_multiple
      Divesite.where(id: params[:site_id]).destroy_all
        redirect_to admin_divesites_path,
        notice: "Divesite(s) Successfully Deleted"
    end

    protected

    def divesite_params
      params.require(:divesite).permit(:name, :region, :country, :latitude, :longitude,
        :description, :surrounding_area, :rating, :water_temperature, :visibility,
        :month_ids => [], :category_ids => [], :medium_ids => [])
    end
  end
end

app/controllers/divesites_controller.rb
class DivesitesController < ApplicationController

  def index
    if params[:q]
      @divesites = Divesite.search(params[:q])
      @divesites.includes([:categories, :months])
    else
      @divesites = Divesite.includes([:categories, :months])
    end
  end

  def show
    @divesite = Divesite.find(params[:id])
    @divesite_images = @divesite.media.all
  end
end

app/views/divesites/_display.html.erb
<% if @divesites %>
<table>
  <th width = "150"> Site Name </th>
  <th width = "150">Country</th>
  <th width = "200">Best Known For</th>
  <th width = "200">Best Months to Dive</th>
  <th width = "100">Overall Rating</th>

<% @divesites.each do |site|%>
  <tr>
    <td><%= link_to site.name, divesite_path(site.id) %></td>
    <td><%= site.country%></td>
    <td>
        <%site.categories.each do |category|%>
        <%= link_to category.name, category_path(category)%><br>
        <%end%>
    </td>
    <td>
        <%site.months.each do |month|%>
        <%= link_to month.name, month_path(month)%><br>
        <%end%>
    </td>
    <td><%= site.overall_rating%></td>
  </tr>
<%end%>
</table>
<% else %>
  <p>No divesites matched your query</p>
<% end %>

app/views/divesites/_top_divesites.html.erb
<div class="show-table">
  <table>
    <tr>
      <th> Divesite </th>
      <th> Country <th>
      <th> Overall Rating</th>
      <th> Reviews </th>
    </tr>

    <% @divesites.each do |site|%>
    <tr>
      <td><%= link_to site.name, divesite_path(site) %></td>
      <td><%= site.country %></td>
      <td></td>
      <td><%= site.overall_rating%></td>
      <td><%= link_to "Reviews", divesite_reviews_path(site)%></td>
    </tr>
    <%end%>
  </table>
</div>

app/views/divesites/index.html.erb
<div class="show-header">
  <h1> Search From The Complete List of Divesites </h1>
</div>

<div id="search-form">
  <%=simple_form_for :q, url: search_divesites_path, method: :post, remote: :true do |f|%>
     <%= f.input :name, required: false, label: "Search By Site Name Or Country", label_html:{class: 'search-input'} %>
     <%= f.input :months, collection: Month.all, as: :check_boxes, required: false, label: "Month", label_html:{class: 'search-input'} %>
     <%= f.input :categories, collection: Category.all, as: :check_boxes, required: false, label: "Category", label_html:{class: 'search-input'} %>
    <div class="form-actions">
    <%= f.submit 'Search', class: 'button small'%>
    </div>
  <%end%>
</div>

<div id="total-list"><%= render 'divesites/display'%></div>

app/views/divesites/index.js.erb
 $('#total-list').html("<%= escape_javascript(render("display"))%>");

app/views/divesites/show.html.erb
<div class="row">
  <div class="site-header">
    <h1><%= @divesite.name %></h1>
    <%if @divesite.region != ""%>
    <h3><%= @divesite.region %> <h3>
    <%end%>
    <h3>, <%= @divesite.country%><h3>
  </div>

  <div class="site-attributes">
    <strong> Best Known For:</strong></br>
      <% @divesite.categories.each do |category|%>
      <li class="button"><%=link_to category.name, category_path(category)%></li>
    <%end%></br>

    <strong> Best Month(s) of the Year to Dive:</strong></br>
      <% @divesite.months.each do |month|%>
      <li class="button"><%=link_to month.name, month_path(month)%></li>
    <%end%>
  </div>

  <ul class="orbit-image" data-orbit data-options="animation: slide, timer_speed: 1000;">
    <% @divesite.media.each do |p|%>
    <li><%= image_tag p.image.url.to_s %></li>
    <%end%>
  </ul>

  <p class="text-justify">
    <strong>Description:</strong></br>
    <%= simple_format(@divesite.description) %>
  </p>

  <p class="text-justify">
    <%if @divesite.surrounding_area != ""%>
      <strong>Surrounding Area:</strong></br>
      <%= @divesite.surrounding_area %>
    <%end%>
  </p>

  <ul class="small-block-grid-2">
    <%if @divesite.water_temperature != ""%>
      <li class="text-left">
        <strong>Average Water Temperature:</strong>
        <%= @divesite.water_temperature %>
      </li>
    <%end%>

    <%if @divesite.visibility != ""%>
      <li class="text-right">
        <strong>Average Visibility:</strong>
        <%= @divesite.visibility %>
      </li>
    <%end%>
  </ul>

  <p class="text-center">
    <strong><%= link_to 'See All Reviews', divesite_reviews_path(@divesite)%></strong>
  </p>
</div>