config/routes.rb
DiveIn::Application.routes.draw do

  devise_for :users
  root "home#index"

  get 'home' => "home#index"
  get 'about' => "home#about"

  resources :categories, only:[:show] do
    resources :divesites, only:[:index]
  end

  resources :months, only:[:show] do
    resources :divesites, only:[:index]
  end

  resources :divesites, only:[:index, :show, :search] do
    resources :reviews
    collection do
      post 'search', to: 'divesites#index'
    end
  end

  namespace :admin do
    resources :divesites do
      resources :media, only: [:new, :create, :destroy]
      collection do
        delete 'destroy_multiple'
      end
    end
    resources :homes, only:[:index]
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :find_divesite

  def index
    @reviews = @divesite.reviews
  end

  def new
    @review = Review.new
  end

  def create
    @review = @divesite.reviews.build(review_params)
    if @review.save
      redirect_to divesite_reviews_path(@divesite),
      notice: "Review Successfully Submitted!"
    else
      render new,
      notice: "Oops something went wrong. Please try again"
    end
  end

  protected

  def find_divesite
    @divesite = Divesite.find(params[:divesite_id])
  end

  def review_params
    params.require(:review).permit(:title, :body, :rating, :date, :user_id, :divesite_id)
  end
end

app/views/reviews/index.html.erb
<div class = "show-header">
  <h1>Reviews for <%=@divesite.name%></h1>
  <% if user_signed_in?%>
    <p align="center"><%= link_to 'Submit a Review', new_divesite_review_path(@divesite)%></p>
  <%end%>
</div>

<div class = "review-table">
  <% @reviews.each do |review|%>
  <table>
    <tr>
      <td><strong><%= review.title %></strong></td>
      <td align="right">Overall Rating: <%= review.rating %></td>
    </tr>
    <tr>
      <td colspan="2"><%= review.body%></td>
    </tr>
    <tr>
      <td>Date of Dive: <%= review.date%></td>
    </tr>
  </table>
  <%end%>
</div>

<p class="text-center"><strong><%= link_to "Back to Divesite", divesite_path(@divesite)%></strong></p>

app/views/reviews/new.html.erb
<div class='admin-form'>
  <%= simple_form_for [@divesite, @review] do |f| %>

    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.input :rating, collection: 1..5 %>
    <%= f.input :date%>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :divesite_id, :value => @divesite.id %>
    <%= f.button :submit %>
  <%end%>
</div>